config/routes.rb
Rails.application.routes.draw do

  resources :transactions

  resources :accounts
  get '/help' => 'static_pages#help', as: 'help'
  get '/about' => 'static_pages#about', as: 'about'
  get '/temp' => 'static_pages#temp', as: 'temp'

  devise_for :users

  resources :users do
    member do
        get 'transactions'
      end
  end

   root 'static_pages#index'

end

app/views/shared/_navigation.html.erb
<div class="container-fluid">

  <!-- Left Menu Side -->
  <div class="navbar-header">
    <!-- Toggle Button visible for Extra Small Devices -->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!-- Brand Logo -->
    <%= link_to "eBanco", root_path, class: "navbar-brand" %>
  </div>

  <!-- Right Menu Side -->
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <!-- Left Menu Items -->
    </ul>
    <ul class="nav navbar-nav navbar-right user-nav">
      <!-- Right Profile Menu Items -->
      <li><%= link_to "Ayuda", help_path %></li>
      <li><%= link_to "Acerca de", about_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right not-nav">
      <!-- Right Menu Notification Items -->
      <% if current_user %>
      <li><%= link_to current_user.email, edit_user_registration_path %></li>
      <li><%= link_to "Cerrar Sesiòn", destroy_user_session_path, :method => "DELETE"  %></li>
      <% else %>
      <li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>


</div>