config/routes.rb
Rails.application.routes.draw do

  resources :transactions

  resources :accounts
  get '/help' => 'static_pages#help', as: 'help'
  get '/about' => 'static_pages#about', as: 'about'
  get '/temp' => 'static_pages#temp', as: 'temp'

  devise_for :users

  resources :users do
    member do
        get 'transactions'
      end
  end

   root 'static_pages#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.most_recent
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)


      respond_to do |format|
      if @transaction.valid?

          if @transaction.money_transfer
          # if @transaction.save
            format.html { redirect_to @transaction, notice: 'La transacción ha sido creada exitosamente.' }
            format.json { render :show, status: :created, location: @transaction }
          else
            format.html { render :new }
            format.json { render json: @transaction.errors, status: :unprocessable_entity }
          end
      else
        format.html { render :new, notice: 'La transacción no es válida.' }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:amount, :concept, :user_id, :account_number)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%= f.label :amount, "Monto" %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :concept, "Concepto" %><br>
    <%= f.text_field :concept %>
  </div>
  <div class="field">
    <%= f.label :account_number, "Número de Cuenta" %><br>
    <%= f.number_field :account_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/new.html.erb
<h1>Realizar Transacción</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Monto:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @transaction.concept %>
</p>

<p>
  <strong>Cuenta:</strong>
  <%= @transaction.account.number%>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>