config/routes.rb
Rails.application.routes.draw do

  resources :transactions

  resources :accounts
  get '/help' => 'static_pages#help', as: 'help'
  get '/about' => 'static_pages#about', as: 'about'
  get '/temp' => 'static_pages#temp', as: 'temp'

  devise_for :users

  resources :users do
    member do
        get 'transactions'
      end
  end

   root 'static_pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
  <title>eBanca | <%= yield(:title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="head-nav" class="navbar navbar-default navbar-fixed-top">
  <%= render 'shared/navigation' %>
</div>

<div id="cl-wrapper">
  <% if current_user %>
  <div class="cl-sidebar">
    <div class="cl-sidebar">
      <!-- Collapse Toggle -->
      <div class="cl-toggle"><i class="fa fa-reorder"></i></div>

      <!-- Menu Items -->
         <div class="side-user">
                <div class="avatar"><a href="<%= root_url %>"> <%= image_tag gravatar_url(current_user) %></a>   </div>
                <div class="info">
                  <a href="<%= root_url %>"><%= current_user.first_name %></a>
                 <%= image_tag 'state_online.png' %> <span>Online</span>
                </div>
        </div>
      <div class="cl-navblock">


        <ul class="cl-vnavigation">
          <li class="parent open"><a href="#"><i class="fa fa-home"></i><span>Consultas</span></a>
            <ul class="sub-menu" style="display: block;">
              <li> <%= link_to "Información de Usuario y Sesión", user_path(current_user) %></li>
              <li> <%= link_to "Saldo", current_user.account %></li>

              <li> <%= link_to 'Historico de Transacciones', transactions_user_path(current_user) %>
            </ul>
          </li>
          <li class="parent open"><a href="#"><i class="fa fa-home"></i><span>Transferencias</span></a>
            <ul class="sub-menu" style="display: block;">
              <li> <%= link_to 'Nueva Transferencia', new_transaction_path %>
            </ul>
          </li>
        </ul>


      </div>
    </div>
  </div>
  <% end %>

  <div class="container-fluid" id="pcont">
    <div class="page-head">
      <h2><%= yield(:title) %> </h2>
    </div>

    <div class="cl-mcont">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </div>

</div>

</body>
</html>